### ISSUE TITLE
Autoplay doesn't work on mobile device

### ISSUE THREAD

**Issue by slezas** [nocodeco/Bubble-Plugin-Video.js#1]
Hey, nice plugin.
Video.js Autoplay only works sometimes on mobile device,

**Comment by will-ks** [comment]
Per https://github.com/videojs/video.js/issues/4927

"This is a browser limitation. Mobile browsers (and soon some desktop browsers as well, Safari already and desktop Chrome with version 66) disallow playing back video with audible audio. If you mute the video, you should be able to autoplay, otherwise, you cannot autoplay on mobile devices."

You might be able to get around this by starting the playback from workflows, on a "Page is loaded" action
